swipe:
  3:
    left:
      command: 'xdotool keydown ctrl+alt+Right; xdotool keyup Right; sleep .3; xdotool keyup ctrl+alt'
    right:
      command: 'xdotool keydown ctrl+alt+Left; xdotool keyup Left; sleep .3; xdotool keyup ctrl+alt'
    up:
      command: 'xdotool keydown ctrl+alt+Down; xdotool keyup Down; sleep .3; xdotool keyup ctrl+alt'
    down:
      command: 'xdotool keydown ctrl+alt+Up; xdotool keyup Up; sleep .3; xdotool keyup ctrl+alt'
  4:
    left:
      command: 'xdotool key alt+Right' # History forward
    right:
      command: 'xdotool key alt+Left' # History back
    up:
      command: 'xdotool key ctrl+t' # Open new tab
    down:
      command: 'xdotool key ctrl+w' # Close tab
pinch:
  2:
    in:
      command: 'xdotool keydown ctrl click 4 keyup ctrl'
    out:
      command: 'xdotool keydown ctrl click 5 keyup ctrl'
