default-cache-ttl 28800

pinentry-program /opt/homebrew/bin/pinentry-mac

# Uncomment the following line for JetBrains IDE integration on macOS
#pinentry-program /Users/florian/.gnupg/pinentry-ide.sh
