#!/usr/bin/env ruby
#
# Night Mode - toggle light/dark theme
#

# TODO: set Redshift
# TODO: set Terminator theme
# TODO: set IntelliJ theme (https://plugins.jetbrains.com/plugin/14076-auto-dark-mode)
# TODO: set keyboard backlight

require "optparse"

# For icon names, see gtk3-icon-browser
CONFIGURATION = {
  day: {
    theme: {
      gtk: "Orchis-red-light-compact",
      wm: "Materia-light",
    },
    icon: "weather-clear",
  },
  night: {
    theme: {
      gtk: "Orchis-red-dark-compact",
      wm: "Materia-dark",
    },
    icon: "weather-clear-night",
  },
}

class Application
  attr_reader :options

  def initialize(args = ARGV)
    @options = {
      # TODO: current state
      mode: CONFIGURATION.keys.find { |k| CONFIGURATION[k][:theme][:gtk] == gtk_theme }.to_s,
    }

    parser = OptionParser.new do |o|
      o.on("-t", "--toggle", "Toggle") do
        options[:mode] = (options[:mode] == "day" ? "night" : "day")
      end

      o.on("-m", "--mode=MODE", "Set day or night mode") do |arg|
        options[:mode] = arg
      end
    end

    parser.banner = "#{$PROGRAM_NAME} [options]"
    parser.on_tail "-h", "--help", "Show help" do
      puts parser
      exit 1
    end

    parser.parse!(args, into: @options)
  end

  def start
    return if gtk_theme == mode[:theme][:gtk]

    # Set GTK theme
    self.gtk_theme = mode[:theme][:gtk]

    # Set window manager theme
    self.xfwm_theme = mode[:theme][:gtk]
    self.compiz_theme = mode[:theme][:wm]
  end

  def to_s
    <<~HERE
      <tool>Click to toggle night mode</tool>
      <icon>#{mode[:icon]}</icon>
      <iconclick>#{$PROGRAM_NAME} --toggle</iconclick>
    HERE
  end

  private

  def mode
    CONFIGURATION.fetch(options[:mode].to_sym)
  end

  def gtk_theme
    `xfconf-query --channel xsettings -p /Net/ThemeName`.strip
  end

  def gtk_theme=(value)
    `xfconf-query --channel xsettings -p /Net/ThemeName -s #{value}`
  end

  def xfwm_theme=(value)
    `xfconf-query --channel xfwm4 -p /general/theme -s #{value}`
  end

  def compiz_theme=(value)
    `gsettings set org.gnome.desktop.wm.preferences theme #{value}`
  end
end

application = Application.new
application.start
puts application
