#!/usr/bin/env bash
#
# Sync system configuration to dotfiles repository
#

# Sync /etc
REPO="$HOME/.etc/"

FILES=$(find "${REPO}" -type f -not -path "${REPO}sync.sh")

for FILE in ${FILES[@]}; do
	SYSTEM=${FILE/$REPO/\/etc\/}

	cp -v "${SYSTEM}" "${FILE}"
done

# Sync /boot
REPO="$HOME/.boot/"

cp -v /boot/grub/grub.cfg ${REPO}/grub/grub.cfg
